apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-web-app
  template:
    metadata:
      labels:
        app: node-web-app
    spec:
      containers:
      - name: node-web-app
        image: node-web-app
        imagePullPolicy: Never  # 本地镜像
        ports:
        - containerPort: 8080
